### ISSUE TITLE
Sugartags waste Mithril's tag cache

### ISSUE THREAD

**Issue by Satyam** [jsguy/misojs#12]
Mithril keeps a cache of created nodes indexed by the first argument to the `m` method.  The more constant attributes you can pile up in the first argument, the best.

This: `m('.item')` is best than `m('div', {class:'item'})` because in the first case Mithirl will clone a `div` node with the `class` attribute already set while in the second it will clone a generic `div` and then waste time adding the `class` attribute.

**Comment by jsguy** [comment]
Hmmm interesting - I'll see if I can optimise on that, thanks! :+1:

**Comment by jsguy** [comment]
I've added a task for this in the sugartags project:

https://github.com/jsguy/mithril.sugartags/issues/5

So I'll close this for now.
