### ISSUE TITLE
client/miso.js confusing version control

### ISSUE THREAD

**Issue by ilikedata** [jsguy/misojs#14]
Editing the mvc/home.js file to reflect the appropriate changes I wanted to make while running the miso server caused client/miso.js to be updated to reflect the changes.

This caused some confusion when looking at modified files within version control.

It appears possible to remove client/miso.js without causing issues (is regenerated if needed). Possibly worth adding client/miso.js into .gitignore?

**Comment by jsguy** [comment]
Yeah good idea, I'll do that now!
