### ISSUE TITLE
Error when trying to run a newly created app

### ISSUE THREAD

**Issue by necrodome** [jsguy/misojs#16]
The first time I try to run a project after creating it with  `miso -n myApp -s todo`
`miso run` errors out with 

`/projects/misoApp/system/index.js:342
				throw error
				      ^
Error: Command failed: /bin/sh -c browserify ./system/main.js >./client/miso.js
Error: Parsing file /Users/necrodome/projects/misoApp/system/main.js: Unexpected token (11:20)`

Checking the main.js file, I saw that generated restrictObject escapes quotes as in:

`var restrictObj = ({&quot;_COMMENT&quot;:&quot;Default is allow: '*', if you specify an 'allow', it will override&quot;,&quot;_COMMENT2&quot;:&quot;If you specify an 'allow', it will override&quot;,&quot;app&quot;:{&quot;todo.index&quot;:{&quot;deny&quot;:[&quot;finance&quot;,&quot;support&quot;]},&quot;hello.edit&quot;:{&quot;deny&quot;:&quot;*&quot;,&quot;allow&quot;:[&quot;support&quot;]}},&quot;db&quot;:{&quot;_COMMENT&quot;:&quot;Ok, we need to figure out how to secure stuff&quot;,&quot;_COMMENT2&quot;:&quot; - we now have a generic 'find' method&quot;,&quot;_COMMENT3&quot;:&quot; - what we really want to do is lock down specific&quot;,&quot;_COMMENT4&quot;:&quot; models, so let's try to use that...&quot;,&quot;/find&quot;:{&quot;todo.index.todo&quot;:{&quot;allow&quot;:[&quot;admin&quot;,&quot;support&quot;]}}}});`

`$ node -v                                                                                                                                                                         
v0.12.0
`

**Comment by jsguy** [comment]
Hmmm interesting - I can reproduce the issue, I should have a fix soon.

**Comment by jsguy** [comment]
Ok, this is fixed in release 0.0.11, please update.
It is a change in the rendering library that broke JSON rendering - the lesson is: always specify the exact version you need in package.json dependencies :)

**Comment by necrodome** [comment]
Thank you. I can confirm it is fixed.
