### ISSUE TITLE
Use Koa instead of Express?

### ISSUE THREAD

**Issue by andyhu** [jsguy/misojs#17]
Recently I switched from using express to koa for all my projects and was amazed by how my life is easier, especially when considering there's no need to deal with callback hell any more.
I wonder if there's a chance that this project will consider to use koa at some point in the future? That would be really awesome!

**Comment by jsguy** [comment]
Yeah I've considered that, but didn't really see the benefits over Express - what do you like better about Koa? I usually solve the callback spaghetti problem by using async, and find generators to be a little counter-intuitive in some circumstances.

Is there anything other than the generators feature that you like about Koa?

**Comment by andyhu** [comment]
Actually I used to have similar thoughts about co / generator thing and use both async and bluebird all the time until I actually tried Koa. Basically the reasons I prefer co / generator to async / bluebird are:

1. IMHO it is rather much intuitive and less verbose code. Writing async code is not much different than writing sync code (the only difference is that it should be wrapped in a generator function and called with co, and use a yield keyword). I found that after switching to Koa my productivity improved more than 50%. For implementing same functionality, it uses around 2/3 lines of code than async.
2. Way better error handling. You can just try catch it when there's any errors and there's no need to worry about if(err) cb(err) thing. Also the debug process is much more simpler.
3. Flexibility. Koa is very concise in its core and the code is more clever and well considered. For example you can use `this.body = [String | Readable Stream | Object]`. it will automatically detect the type of the input and send appropriate content and headers.
4. Future proof. co / generator solution is a step stone to ES7 async / await. It's very easy to switch to ES7 async when you use co.

If you consider ES6 may have compatibility issues (both in the browser or lower version of node.js) then babel (formerly name 6to5) is the cure. It can automatically transpile ES6 code to ES5.

With regards to the routing pattern, I actually looked into it before. And I found that the one Mithril uses is mostly the same as Express except there are some minor differences. Koa itself actually doesn't have a routing system build-in to keep flexibility. You can choose any routing system you like. There are a few user contributed routing modules to choose. If you prefer exactly same behaviors as Express, there's at least one module can do that. But if you decide to write your own routing solution to make sure it is 100% compatible with Mithril, Koa is easier to implement. So I would consider it's an advantage for Koa over Express.

**Comment by andyhu** [comment]
I'm actually building a framework based on Koa. Koa itself is similar as connect rather than batteries included Express. So you need to choose a few modules to

**Comment by andyhu** [comment]
Oops.. sorry I clicked the wrong button

**Comment by jsguy** [comment]
Thanks for your detailed response, I appreciate it.

* The better error handling would be nice - at the moment I'm try/catching around user created actions, but that doesn't stop async code from throwing.
* The use of something like babel is nice, but it will most likely blow out the small footprint on the client side - I accidentally added lodash the other day, and suddenly the client-side footprint tripled, which is something that I am quite vary of. Of course, users are more than welcome to add whatever they require, as a small footprint might not be important to them.
* Good to know about the Koa routing situation - that probably means it won't be too hard to find something that matches mithril

You've hit the nail on the head with the last point - at the moment it is all about isomorphism, and making it easier to work with that, so hopefully using Express shouldn't get in the way - I'd consider using Koa in the future, once the isomorphic nature of things is sorted, and when it can be implemented without blowing out the small footprint.

**Comment by StephanHoyer** [comment]
Well said, @jsguy 

Also I don't want to bother people with an other thing to reason about. The Backend side of the projects is not as crucial to the project.

So let's stick to express since most people know that.

Feel free to fork this and offer an Koa version.

PS: I also did a lot with Koa. It's nice and clean. But like u said, `async` `await` knocks on the door and using generators for that is pretty much a quirks. So I switched back to express and use promises to detangle the cb-mess. In fact it's not a real mess if done right.

**Comment by andyhu** [comment]
Thanks guys, I think that makes sense. It's better to keep focus on the most important part. I'm working on a framework which wraps all common koa related modules together to make it more like Express, but with isomorphic rendering and user system built in. If you don't mind I may fork it into a Koa version and play with it a bit. Thanks again for your great work!

**Comment by jsguy** [comment]
@andyhu Sounds good - and there is no reason that parts of miso couldn't become abstracted into a library, so if you find something really useful that you'd like to be able to use, we could definitely look at that.

**Comment by jsguy** [comment]
Good discussion guys, I'm closing this now, as I like to keep a clean slate of issues.
