### ISSUE TITLE
Barebones skeleton

### ISSUE THREAD

**Issue by necrodome** [jsguy/misojs#18]
Is there a barebones skeleton for a new project, without the baggage of todo example? What's the best way to start a new project without all that baggage? I don't know if that's too much, but a document describing how to develop the todo app from scratch would be very useful.

**Comment by jsguy** [comment]
Not yet, I'm still working on that, I'll use the todo app for the "getting started" article, would you be interested in helping me proof read it in a day or two when ready?

For now, you can simply delete the files you don't want - and update /cfg/routes.json for any manually mapped routes that you remove. Long term the skeletons will be much cleaner and concise.

**Comment by necrodome** [comment]
> would you be interested in helping me proof read it in a day or two when ready?

Sure, shoot me a mention/email when it is ready.

**Comment by jsguy** [comment]
@necrodome Here is a draft:

https://github.com/jsguy/misojs/wiki/!DRAFT!-Getting-started

It shows how to build a "hello world" app, and I've started on the todo part as well.

Would you be able to have a look, and let me know if the hello world part makes sense, and if the instructions are clear enough to follow, and get up and running?

**Comment by necrodome** [comment]
Thanks, I think it is good for starters but there is a huge gap transferring from  the hello world app to todo app (I guess that's because you are using todo skeleton) I think what a dev would need is how would you go creating the todo app without the skeleton? How would he create the necessary api calls? How does api.server.js generated and how someone can add his own api calls? etc

**Comment by jsguy** [comment]
My thinking was that the hello world app is very similar to the todo app in structure, (using the single url pattern), and so it would be easy to transition across.

I've intentionally not done the usual build it step-by-step, as personally I find those tedious, but perhaps that is what I need to include here - I've spent a fair bit of time with the code, so I probably know it a little too well :)

I'll update the todo section to be step-by-step.

**Comment by jsguy** [comment]
Hi @necrodome! 

I've made some progress - I split the getting started and the todo app articles:

https://github.com/jsguy/misojs/wiki/Getting-started

At the bottom there is a link to read the todo app article:

https://github.com/jsguy/misojs/wiki/Creating-a-todo-app

I'd appreciate some feedback on the following:

1. Can you get up and running with the getting started app? ie: does the article "flow" right, and is easy enough to get up and running?
2. Does what I've written so far for the todo article go into enough details?

I've still got a way to go on the todo article, but I consider the getting started article done. I'm also considering doing an article after the todo app, that shows how the user app works, and the difference with [Single url](https://github.com/jsguy/misojs/wiki/Patterns#single-url-mvc) vs [Multi url](https://github.com/jsguy/misojs/wiki/Patterns#multi-url-mvc) patterns. For medium to large apps, the multi-url pattern is better, as you can deep-link, and it is easier to test individual actions when they are exposed separately.

As far as the skeletons go, I need to clean them up a little, so that when you use them, there is just one set of files mapped to the root of the app, so that it's a little cleaner.

Anyway, let me know what you think so far :)

**Comment by necrodome** [comment]
Thanks, @jsguy. I think this is very good. The getting started article flows nicely, and once generated code matches the article (ie no hello.js on generation so one can copy-paste to test it himself), I think it will be done. Looking forward to persistence section for todo app.

**Comment by jsguy** [comment]
@necrodome - the first part of the todo is ready for review, please have a look and see if it makes sense:

https://github.com/jsguy/misojs/wiki/Creating-a-todo-app

**Comment by jsguy** [comment]
Hi @necrodome,

I've cleaned up the skeleton functionality, and added the 2nd part to the todo app here:

https://github.com/jsguy/misojs/wiki/Creating-a-todo-app-part-2-persistence

Let me know what you think.

**Comment by necrodome** [comment]
Thanks a lot, @jsguy. This reads nicely and covers what I expected.

I have been playing with the adaptors to see how I can add new calls. What I did was add a test function to flatfile adaptor as in:

```javascript
test: function(cb, err, args) {
    console.log("testing adding methods " + JSON.stringify(args));
    cb("received response from server " + Date.now());
}
```

Once I saved, the code generated automatically for client and server. To test the functionality (both client side and server side rendering), I added to controller:

```javascript
 ctrl.test = function() {
     db.test({
         type: 'todo.index.todo'
     }).then(function(resp) {
         ctrl.info = resp.result
     })
 };
 ctrl.info = "Info Text";

 db.test({
     type: 'todo.index.todo'
 }).then(function(resp) {
     ctrl.info = resp.result
 });
```

and to view:
```javascript
 BUTTON({onclick: ctrl.test}, "Test"),
 DIV(ctrl.info)
```

Is this the right way to use the persistence api? A section in the docs would be helpful for that.

**Comment by jsguy** [comment]
@necrodome Yeah what you've done there will work, however I'm working on the adaptors to make it a little better - there will be 2 ways to do it:

1. Extend an existing adaptor - I'll create an `extend` method for this
2. Create an adaptor from scratch

I'll be documenting it all - basically they are going to be fairly thin wrappers around whatever the underlying data store is.
You will be able to do something like:

```javascript
var db = require(... whatever adaptor ...);
db.extend(function(obj){
	//	obj will contain adaptor specific things, for example
	//	access to mongoose, etc...
	return {
	    test: function(cb, err, args) {
	        console.log("testing adding methods " + JSON.stringify(args));
	        cb("received response from server " + Date.now());
	    }
	};
});
```

This will be a little more flexible than the current solution.

**Comment by jsguy** [comment]
@necrodome I've added the ability to extend adaptors, documentation here:

https://github.com/jsguy/misojs/wiki/Adaptors

Let me know what you think...

**Comment by necrodome** [comment]
Thanks a lot, @jsguy. This is helpful. I was trying to add my adaptor (for firebase), but files weren't generated until I changed adaptor config in server.json. (Is that so?) I was going to add a section to https://github.com/jsguy/misojs/wiki/Adaptors for creating adaptors, but I wanted to make sure if this is the correct flow.

**Comment by jsguy** [comment]
Adaptors need to be activated in the server.json config file as it takes quite a while to create the end-points when the app starts up - I'm going to include a bunch of adaptors by default, so it is important that you only switch on what you need.
I've been considering making adaptors a separate project, and that might happen in the future, but whilst I'm still making changes to the architecture, it is better to leave it as a part of the main project.

So, for your firebase adaptor, put it in /modules/adaptors for now, and when you're happy with it, I can add it as an official adaptor if you like :)

I'm going to update that wiki page now - I've got a draft that I've been meaning to finish on it...

**Comment by jsguy** [comment]
@necrodome I've updated the page with a section on custom adaptors - it's a little brief, so feel free to add details if you have time:

https://github.com/jsguy/misojs/wiki/Adaptors#creating-custom-adaptors

Note: the flickr example is now in master, grab it and have a play around if you like.
