### ISSUE TITLE
working with the repo

### ISSUE THREAD

**Issue by necrodome** [jsguy/misojs#21]
I am trying the steps at https://github.com/jsguy/misojs/#clone-repository-method

Now, the generated client-server code is not included, bin/miso run command fails with Error: Cannot find module '../system/adaptor/flatfiledb/api.server.js' in mvc files. 

Is there a way to generate the files before starting the app?

**Comment by jsguy** [comment]
@necrodome That is now fixed - adaptors are now generated before we start the controllers.

**Comment by jsguy** [comment]
Note: when developing miso, you may need to manually restart the server, as we're not watching all system files, as that is a little too resource intensive.
