### ISSUE TITLE
'touch' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by vaughanwatson** [jsguy/misojs#27]
Miso version 0.0.26, Environment: development 
When typing miso run the following error message comes up.
**'touch' is not recognized as an internal or external command, operable program or batch file.**
**RESOLVED BY:** Within project directory run npm install --save touch-cli

**Comment by jsguy** [comment]
Oh - you must be using windows?

**Comment by zakiryousufi** [comment]
I cant solve this problem that touch is not recognized as an internal or external command, operable program or batch file.

**Comment by jsguy** [comment]
Are you able to create a JSBin to demonstrate the problem?

http://jsbin.com

**Comment by Hasan2323** [comment]
Just run it through the GitBash terminal on windows and it works fine

**Comment by AnasOkasha-chambaam** [comment]
npm install touch-cli -g

it solved the problem for me

**Comment by MahmoudAbdElTawab** [comment]
echo.>index.html

**Comment by deepak4240** [comment]
It is possible to do in windows
1. First download the below link.
2. Then extract that and you need to paste that in C:\
3. Cut that and Go to local disk C:\ > Program files > cmd > paste here
4. Now your 'touch' command will work now.
(https://sourceforge.net/projects/touchforwindows/)

**Comment by urdadx** [comment]
If you already have Git installed, then you also have **GIT BASH** installed too... To solve this problem navigate to your project directory using the **GIT BASH** Terminal and try again using " touch Procfile ". It should work perfectly.

**Comment by vishal-beep** [comment]
> npm install touch-cli -g
> 
> it solved the problem for me

yes it's working

**Comment by mwanawabangona** [comment]
It is possible to do in windows

First, download the below link.
Then extract that and you need to paste that in C:\
Cut that and Go to local disk C:\ > Program files > cmd > paste here
Now your 'touch' command will work now.
(https://sourceforge.net/projects/touchforwindows/) or use
GIT BASH instead.

**Comment by iiitbh18** [comment]
> npm install touch-cli -g
> 
> it solved the problem for me

Thank you

**Comment by Nimadoustdar** [comment]
Fixed after running this command:

npm install touch-cli -g
After that you can run this for example:

touch index.html

**Comment by wnm-trojan** [comment]
if you are use windows

**Comment by wnm-trojan** [comment]
if you are use windows

**Comment by wnm-trojan** [comment]
If you are use windows, use this code
type nul > filename.extension
e.g. type nul > app.py

**Comment by israel-oye** [comment]
> If you are use windows, use this code type nul > filename.extension e.g. type nul > app.py

This worked. Thankee

**Comment by SparshMaheshwari15** [comment]
> npm install touch-cli -g
> 
> it solved the problem for me

it's showing a error 
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by safin777** [comment]
>run this "touch webpack.mix.js" on git bash . It works for me in this way

**Comment by Hawk3037** [comment]
type : Cannot find path 'C:\Users\HawkI\OneDrive\Desktop\calculator\nul' because it does not exist.
At line:1 char:1
+ type nul > index.js
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\HawkI\...\calculator\nul:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
    this eroor coming , itried everything

**Comment by Hawk3037** [comment]
touch index,js

touch : File C:\Users\HawkI\AppData\Roaming\npm\touch.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see 
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ touch index,js
+ ~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by TampaJoey** [comment]
> Just run it through the GitBash terminal on windows and it works fine

Perfect. Thank You!
